services:
  - type: web
    name: les-forum
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: forum-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
